### ISSUE TITLE
LUIS ai response with status code: 400

### ISSUE THREAD

**Issue by singhabhi13** [CatalystCode/rapid-voice-commands-ios#1]
Hi There,
I followed the instruction and used this sample code. It worked for first using iOS speech recognition. Post that I do not get proper response from LUIS service. I created fresh application on LUIS web interface updated the application id in my code but no luck. Below is the response from LUIS

Note: The app id and the subscription key is hidden in the post.

Printing description of response:
<NSHTTPURLResponse: 0x170230280> { URL: https://api.projectoxford.ai/luis/v1/application?id=9982f326XXXXXXXX950be&subscription-key=3492XXXXXXXXXX55&q=Book%20book%20a%20flight%20to%20Mumbai } { status code: 400, headers {
    "Cache-Control" = "no-store, proxy-revalidate, no-cache, max-age=0, private";
    "Content-Length" = 75;
    "Content-Type" = "application/json; charset=UTF-8";
    Date = "Wed, 01 Mar 2017 12:41:29 GMT";
    Pragma = "no-cache";
    "Strict-Transport-Security" = "max-age=31536000; includeSubDomains; preload";
    "X-Powered-By" = "ASP.NET, ARR/3.0, ASP.NET";
    "apim-request-id" = "491bdae4-bd5c-4c60-ab85-80e798570331";
    "proxy-request-id" = "15a4321e-4476-43bf-8ce3-d072a5af0bf8";
} }
Printing description of json:
<nil>
2017-03-01 18:11:47.474971 RapidVoiceCommands[474:97904] Could not parse loaded json with error:Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}

**Comment by phongcao** [comment]
Hi @singhabhi13, this issue will be fixed in the next update. Meanwhile, you can try updating the **luisString** to the new endpoint:

``
NSString * luisString = [NSString stringWithFormat:@"https://api.projectoxford.ai/luis/v2.0/apps/%@?subscription-key=%@&q=%@", _luisAppId, _luisSubscriptionId, encodedQuery];
``

And remember to use the [Programmatic API Key](https://www.luis.ai/Home/UserSettings) for **LuisSubscriptionId**.

**Comment by singhabhi13** [comment]
Hey @phongcao, new endpoint works. Thank you for the help.
